apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: autoscale

---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: apache-server
     namespace: autoscale
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
         - name: nginx
           image: nginx:latest
           resources:
             limits:
               cpu: "500m"  # 0.5 CPU cores
               memory: "512Mi"
             requests:
               cpu: "200m"  # 0.2 CPU cores
               memory: "256Mi"
